### ISSUE TITLE
This is the best color scheme for MacVim so far

### ISSUE THREAD

**Issue by nyngwang** [cseelus/vim-colors-tone#1]
Feel free to use these pictures at readme!

![image](https://user-images.githubusercontent.com/24765272/112863983-fd840700-90e9-11eb-81be-93e0d8a99224.jpeg)
![image](https://user-images.githubusercontent.com/24765272/112864121-1e4c5c80-90ea-11eb-8ccf-247eceb8de27.jpeg)

**Comment by cseelus** [comment]
Nice, added them to the [README](https://github.com/cseelus/vim-colors-tone/blob/master/README.md).

**Comment by nyngwang** [comment]
@cseelus Hi, long time no see. How is everything going? Hope you doing well! Just finding _old_ things(I mean, good memories), and here is what it looks like now, two years later:

<img src="https://user-images.githubusercontent.com/24765272/222935509-b6a63c83-12c8-4317-9c22-3340d0b3556f.png" width="500">

Again, feel free to use it for promotion, and nice job on this art work!

---

Just did some little variation (only changed `String` and `Comment`):

<img src="https://user-images.githubusercontent.com/24765272/222937298-7d3f7cea-8f47-439c-9568-65edbad041c4.png" width="500">

**Comment by cseelus** [comment]
Hi @nyngwang, everything fine here, hope for you too. Great to hear you still like this colorscheme. I added your new screenshot to the README.

I'm using Neovim these days and have [ported this theme](https://github.com/cseelus/nvim-colors-tone), and also added a light mode, which is (automatically) enabled at daytime, in sync with the operating systems daytime-dependent appearance:


![Screenshot 2023-03-05 at 20 29 41](https://user-images.githubusercontent.com/3188392/222981756-a860c19d-3075-4271-a7c7-f4df3c06033b.png)


![Screenshot 2023-03-05 at 20 23 17](https://user-images.githubusercontent.com/3188392/222981505-ae3f4f77-6332-47e9-8241-5321e1452889.png)

**Comment by nyngwang** [comment]
To @cseelus:

> [...] a light mode, which is (automatically) enabled at daytime, **in sync with** the operating systems daytime-dependent appearance.

I just migrated to the new one you linked and It works well. That's really an amazing idea! Am waiting for the dawn now :)

**Comment by cseelus** [comment]
@nyngwang Many newer Neovim themes support this feature. It requires a few things though:
- Your operating system being able to change appearance from light to dark and vice versa
- Your Terminal supporting this feature, like https://iterm2.com
- A Neovim plugin, that reads the current OS appearance, like https://github.com/will/bgwinch.nvim
